# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

project 'Elo Rate.xcodeproj', 'XCTest' => :debug

source 'git@github.com:JoaoPCampos/frameworks-ios.git'

target 'Elo Rate' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Elo Rate
  pod 'LayoutKit', '~> 1.0.0'
  pod 'SwiftService', '~> 0.1.1'

  target 'Elo RateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
